### ISSUE TITLE
Current issues:

### ISSUE THREAD

**Issue by brimwats** [rsoper/richardsoper.me#15]
Running

> docker-compose up -d

* fails as ghost.env does not exist in /ghost/. I pointed it to the example.env

* HTTPS does not currently work (or I am doing something wrong!).  Navigating all all of the sites throws up the chrome/firefox warning about HTTP/S

* Traefik.URL phpmyadmin.URL and nextcloud.URL all fail. as 404 page not found.

**Comment by rsoper** [comment]
example.ghost.env uploaded. 

Will investigate other issues further

**Comment by brimwats** [comment]
Thanks!

Here's my current setup. I have a domain from Namecheap/DNS from Cloudflare, with the "content" sent to the server IP (port forwarding is done through my provider, exposing 80 443, and such.

![image](https://user-images.githubusercontent.com/49103046/73984719-476ac600-4907-11ea-8088-726619a6c82c.png)

in using your ENV and docker-compose I replaced all the ${DOMAIN} with brimstor.me and the directory path with my ubuntu directory where I downloaded "richardsoper.me" to.

**Comment by rsoper** [comment]
Turns out I screwed up the traefik.yml file and didnt notice since I had cloudflare also issuing certs for the subdomains. This latest merge should have fixed it

**Comment by brimwats** [comment]
I think it might be more broken now :(

Here's what firefox spits back

>Websites prove their identity via certificates. Firefox does not trust this site because it uses a certificate that is not valid for cloud.brimstor.me. The certificate is only valid for 43fb823ca39854d6e377c7a655661683.1585f05103e667716f02b7c5a37dc0cd.traefik.default.
> 6c6c00a66f518675423ee7cfb9d741d1.d381c738851998fab8815edc6029365a.traefik.default.


I'll put my files below so you can peep and see if I'm doing something obviously wrong : 

```
version: "3"

services:
  # Traefik 2.0 reverse proxy with sub-domain configuration

  traefik:
    container_name: traefik
    image: traefik:v2.0
    command: --providers.docker
    restart: always
    environment:
      - CF_API_EMAIL=REALEMAIL@gmail.com
      - CF_API_KEY=SOMEKEY24234234
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /home/MYUSERNAME/Docker/traefik:/etc/traefik
      - /home/MYUSERNAME/Docker/shared:/shared
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik.brimstor.me`)"
      - "traefik.http.middlewares.traefik-auth.basicauth.usersfile=/shared/.htpasswd"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.brimstor.me`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=cf-cert"
      - "traefik.http.routers.traefik.tls.domains[0].main=*.brimstor.me"
      - "traefik.http.routers.traefik.tls.domains[0].sans=brimstor.me"
      - "traefik.http.routers.traefik-secure.service=api@internal"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    networks:
      - traefik_proxy

  #Wordpress acts as the TLD landing. www.richardsoper.me --> richardsoper.me

  wordpress:
    container_name: wordpress
    hostname: wordpress
    image: wordpress:latest
    restart: always
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: TOTALLYREALPASSWORD
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - /home/MYUSERNAME/Docker/wordpress:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.entrypoints=http"
      - "traefik.http.routers.wordpress.rule=Host(`www.brimstor.me`) || Host(`brimstor.me`)"
      - "traefik.http.middlewares.wordpress-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.wordpress.middlewares=wordpress-https-redirect"
      - "traefik.http.routers.wordpress-secure.entrypoints=https"
      - "traefik.http.routers.wordpress-secure.rule=Host(`www.brimstor.me`) || Host(`brimstor.me`)"
      - "traefik.http.routers.wordpress-secure.tls=true"
      - "traefik.http.routers.wordpress-secure.tls.certresolver=cf-cert"
      - "traefik.http.routers.wordpress-secure.service=wordpress"
      - "traefik.http.services.wordpress.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik_proxy"
    networks:
      - traefik_proxy

  # Ghost is the preferred blogging platform for tech related blogs

  ghost:
    container_name: ghost
    image: ghost:latest
    restart: always
    env_file:
      - /home/MYUSERNAME/Docker/ghost/ghost.env
    depends_on:
      - mariadb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ghost.entrypoints=http"
      - "traefik.http.routers.ghost.rule=Host(`blog.brimstor.me`)"
      - "traefik.http.middlewares.ghost-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.ghost.middlewares=ghost-https-redirect"
      - "traefik.http.routers.ghost-secure.entrypoints=https"
      - "traefik.http.routers.ghost-secure.rule=Host(`blog.brimstor.me`)"
      - "traefik.http.routers.ghost-secure.tls=true"
      - "traefik.http.routers.ghost-secure.tls.certresolver=cf-cert"
      - "traefik.http.routers.ghost-secure.service=ghost"
      - "traefik.http.services.ghost.loadbalancer.server.port=2368"
      - "traefik.docker.network=traefik_proxy"
    volumes:
      - /home/MYUSERNAME/Docker/ghost:/var/lib/ghost/content
    networks:
      - traefik_proxy

  # Portainer - WebUI for docker containers

  portainer:
    container_name: portainer
    image: portainer/portainer:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/MYUSERNAME/Docker/portainer/data:/data
      - /home/MYUSERNAME/Docker/shared:/shared
    command: -H unix:///var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.entrypoints=http"
      - "traefik.http.routers.portainer.rule=Host(`portainer.brimstor.me`)"
      - "traefik.http.middlewares.portainer-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.portainer.middlewares=portainer-https-redirect"
      - "traefik.http.routers.portainer-secure.entrypoints=https"
      - "traefik.http.routers.portainer-secure.rule=Host(`portainer.brimstor.me`)"
      - "traefik.http.routers.portainer-secure.tls=true"
      - "traefik.http.routers.portainer-secure.tls.certresolver=cf-cert"
      - "traefik.http.routers.portainer-secure.service=portainer"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.docker.network=traefik_proxy"
    networks:
      - traefik_proxy

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mariadb
    environment:
      - PMA_HOST=mariadb
      # - PMA_USER=root
      # - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PMA_ABSOLUTE_URL=https://phpmyadmin.brimstor.me/
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.phpmyadmin-auth.basicauth.usersfile=/shared/.htpasswd"
      - "traefik.http.routers.phpmyadmin.entrypoints=http"
      - "traefik.http.routers.phpmyadmin.rule=Host(`db.brimstor.me`)"
      - "traefik.http.middlewares.phpmyadmin-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.phpmyadmin.middlewares=phpmyadmin-https-redirect"
      - "traefik.http.routers.phpmyadmin-secure.entrypoints=https"
      - "traefik.http.routers.phpmyadmin-secure.rule=Host(`db.brimstor.me`)"
      - "traefik.http.routers.phpmyadmin-secure.tls=true"
      - "traefik.http.routers.phpmyadmin-secure.tls.certresolver=cf-cert"
      - "traefik.http.routers.phpmyadmin-secure.service=phpmyadmin"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik_proxy"
    networks:
      - traefik_proxy

  # Nextcloud - Personal cloud storage system

  nextcloud:
    container_name: nextcloud
    image: nextcloud:latest
    restart: always
    depends_on:
      - mariadb
    ports:
      - "8000:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.entrypoints=http"
      - "traefik.http.routers.nextcloud.rule=Host(`cloud.brimstor.me`)"
      - "traefik.http.middlewares.nextcloud-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud-https-redirect"
      - "traefik.http.routers.nextcloud-secure.entrypoints=https"
      - "traefik.http.routers.nextcloud-secure.rule=Host(`cloud.brimstor.me`)"
      - "traefik.http.routers.nextcloud-secure.tls=true"
      - "traefik.http.routers.nextcloud-secure.tls.certresolver=cf-cert"
      - "traefik.http.routers.nextcloud-secure.service=nextcloud"
      - "traefik.http.middlewares.nextcloud-secure.headers.customFrameOptionsValue=SAMEORIGIN"
      - "traefik.http.middlewares.nextcloud-secure.headers.framedeny=true"
      - "traefik.http.middlewares.nextcloud-secure.headers.sslredirect=true"
      - "traefik.http.middlewares.nextcloud-secure.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.nextcloud-secure.headers.stsPreload=true"
      - "traefik.http.middlewares.nextcloud-secure.headers.stsSeconds=15552000"
      - "traefik.http.middlewares.nextcloud.headers.customFrameOptionsValue=SAMEORIGIN"
      - "traefik.http.middlewares.nextcloud.headers.framedeny=true"
      - "traefik.http.middlewares.nextcloud.headers.sslredirect=true"
      - "traefik.http.middlewares.nextcloud.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.nextcloud.headers.stsPreload=true"
      - "traefik.http.middlewares.nextcloud.headers.stsSeconds=15552000"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik_proxy"
    volumes:
      - /home/MYUSERNAME/Docker/nextcloud:/var/www/html
    networks:
      - traefik_proxy

  # Gitea - A simple self hosted git server

#  #gitea:
#  #  container_name: gitea
#    image: gitea/gitea:latest
#    restart: always
#    depends_on:
#      - mariadb
#    ports:
#      - "3000:3000"
#      - "2222:22"
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.gitea.entrypoints=http"
#      - "traefik.http.routers.gitea.rule=Host(`git.brimstor.me`)"
#      - "traefik.http.middlewares.gitea-https-redirect.redirectscheme.scheme=https"
#      - "traefik.http.routers.gitea.middlewares=gitea-https-redirect"
#      - "traefik.http.routers.gitea-secure.entrypoints=https"
#      - "traefik.http.routers.gitea-secure.rule=Host(`git.brimstor.me`)"
#      - "traefik.http.routers.gitea-secure.tls=true"
#      - "traefik.http.routers.gitea-secure.tls.certresolver=cf-cert"
#      - "traefik.http.routers.gitea-secure.service=gitea"
#      - "traefik.http.services.gitea.loadbalancer.server.port=3000"
#      - "traefik.docker.network=traefik_proxy"
#    volumes:
#      - /home/MYUSERNAME/Docker/gitea:/data
#    networks:
#      - traefik_proxy

  # Home Assistant

#   homeassistant:
#     container_name: homeassistant
#     image: homeassistant/home-assistant:latest
#     restart: always
#     ports:
#       - "8123:8123"
#     volumes:
#       - /home/MYUSERNAME/Docker/homeassistant/config:/config
#     environment:
#       - TZ=${TZ}
#     labels:
#       - "traefik.enable=true"
#       - "traefik.http.routers.homeassistant.entrypoints=http"
#       - "traefik.http.routers.homeassistant.rule=Host(`home.brimstor.me`)"
#       - "traefik.http.middlewares.homeassistant-https-redirect.redirectscheme.scheme=https"
#       - "traefik.http.routers.homeassistant.middlewares=homeassistant-https-redirect"
#       - "traefik.http.routers.homeassistant-secure.entrypoints=https"
#       - "traefik.http.routers.homeassistant-secure.rule=Host(`home.brimstor.me`)"
#       - "traefik.http.routers.homeassistant-secure.tls=true"
#       - "traefik.http.routers.homeassistant-secure.tls.certresolver=cf-cert"
#       - "traefik.http.routers.homeassistant-secure.service=homeassistant"
#       - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"
#       - "traefik.docker.network=traefik_proxy"
#     networks:
#       - traefik_proxy

 # PiHole - Ad filtering DNS system.

#   pihole:
#     container_name: pihole
#     hostname: pihole
#     image: pihole/pihole:latest
#     restart: always
#     ports:
#       - "53:53/tcp"
#       - "53:53/udp"
#       - "8182:80"
#       - "8183:443"
#     volumes:
#       - /home/MYUSERNAME/Docker/pihole/pihole:/etc/pihole
#       # - /home/MYUSERNAME/Docker/docker/pihole/logs:/var/log/
#       - /home/MYUSERNAME/Docker/pihole/dnsmasq.d:/etc/dnsmasq.d
#     cap_add:
#       - NET_ADMIN
#     environment:
#       - ServerIP=${SERVER_IP}
#       - PROXY_LOCATION=pihole
#       - VIRTUAL_HOST=pihole.brimstor.me
#       - VIRTUAL_PORT=80
#       - TZ=${TZ}
#       - WEBPASSWORD=${PIHOLEPW}
#       - DNS1=1.1.1.1
#       - DNS2=1.0.0.1
#     labels:
#       - "traefik.enable=true"
#       - "traefik.http.routers.pihole.entrypoints=http"
#       - "traefik.http.routers.pihole.rule=HostRegexp(`pihole.brimstor.me`,`pihole.brimstor.me/{catchall:.*}`)"
#       - "traefik.http.middlewares.pihole-https-redirect.redirectscheme.scheme=https"
#       - "traefik.http.routers.pihole.middlewares=pihole-https-redirect"
#       - "traefik.http.routers.pihole-secure.entrypoints=https"
#       - "traefik.http.routers.pihole-secure.rule=HostRegexp(`pihole.brimstor.me`,`pihole.brimstor.me/{catchall:.*}`)"
#       - "traefik.http.routers.pihole-secure.tls=true"
#       - "traefik.http.routers.pihole-secure.tls.certresolver=cf-cert"
#       - "traefik.http.routers.pihole-secure.service=pihole"
#       - "traefik.http.services.pihole.loadbalancer.server.port=80"
#       - "traefik.docker.network=traefik_proxy"
#     networks:
#       - traefik_proxy

  # Watchtower - automatically update docker containers

  watchtower:
    container_name: watchtower
    hostname: watchtower
    restart: always
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 4 * * *" --cleanup

  # MariaDB - SQL based database for most of this stack.

  mariadb:
    container_name: mariadb
    hostname: mariadb
    image: linuxserver/mariadb
    restart: always
    volumes:
      - /home/MYUSERNAME/Docker/mariadb:/config
      - /home/MYUSERNAME/Docker/shared:/shared
    environment:
      - MYSQL_ROOT_PASSWORD=TOTALLYREALPASSWORD
      - TZ="America/New_York"
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external: true
```
example.env

```
# Directory level authentication
HTTP_USERNAME=REALUSERNAME
HTTP_PASSWORD=REALPASSWORD

# My domain name
DOMAINNAME=brimstor.me

# Cloudflare DNS authentication
CLOUDFLARE_EMAIL=ANEMAIL@gmail.com
CLOUDFLARE_API_KEY=REALAUTHKET24234

# Time Zone
TZ="America/New_York"

# Docker directory
DOCKERDIR=/home/USERNAME/Docker

# Database passwords
MYSQL_ROOT_PASSWORD=TOTALLYREALPASSWORD
WORDPRESSPW=TOTALLYREALPASSWORD

# Server IP
SERVER_IP=OMG REAL IP

# PiHole Password
PIHOLEPW=SECRET_PASSWORD
```


ghost.env
```
NODE_ENV=production
url=https://blog.brimstor.me
database__client=mysql
database__connection__host=mariadb
database__connection__user=dbghost
database__connection__password=REALPASSWORD
database__connection__database=dbghost
```
